import Head from "next/head";
import { AppShell } from "@mantine/core";
import { Cronus, Footer, HeaderNavbar, SideNavbarHome } from "../components";
import SideNavbarCronus from "../components/SideNavbarCronus";

export default function CronusPage() {
  return (
    <>
      <Head>
        <title>Evmos-dashLytics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell
        navbar={<SideNavbarCronus />}
        header={<HeaderNavbar />}
        footer={<Footer links={[]} />}
        styles={(theme) => ({
          main: {
            backgroundColor:
              theme.colorScheme === "dark"
                ? theme.colors.dark[8]
                : theme.colors.gray[0],
          },
        })}
      >
        <Cronus />
      </AppShell>
    </>
  );
}
