import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Box } from "@mantine/core";
import { HeaderNavbar } from "../components";

export default function Home() {
  return (
    <Box className={styles.container}>
      <Head>
        <title>Evmos-dashLytics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNavbar links={[]} />
    </Box>
  );
}
