import Head from "next/head";
import { AppShell } from "@mantine/core";
import { Cronus, Footer, HeaderNavbar, SideNavbarHome } from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Evmos-dashLytics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell
        navbar={<SideNavbarHome />}
        header={<HeaderNavbar />}
        footer={<Footer links={[]} />}
        styles={(theme) => ({
          main: {
            backgroundColor:
              theme.colorScheme === "dark"
                ? theme.colors.dark[8]
                : theme.colors.gray[0],
          },
        })}
      >
        <Cronus />
      </AppShell>
    </>
  );
}

{
  /*   const patterFill = useColorModeValue("brand.200", "brand.300");

  <PillPity
        pattern="diagonal-lines"
        patternFill={patterFill}
        bgColor="choc.secondary"
        patternOpacity={0.1}
        padding="0, 2rem"
        minH="100vh"
      > */
}
